services:
  - type: web
    name: server
    runtime: docker
    dockerfilePath: ./server.Dockerfile
    dockerContext: ./

  - type: web
    name: stream-eo
    runtime: docker
    dockerfilePath: ./stream-eo.Dockerfile
    dockerContext: ./

  - type: web
    name: stream-ir
    runtime: docker
    dockerfilePath: ./stream-ir.Dockerfile
    dockerContext: ./
