services:
  - type: web
    name: server
    runtime: docker
    dockerfilePath: ./server.Dockerfile
    image:
      url: bluenviron/mediamtx:latest-ffmpeg
    # env:
    #   # Add environment variables here if needed
    # volumes:
    #   - from: mediamtx.yml
    #     to: /mediamtx.yml
    #   - from: gizmo.mp4
    #     to: /video.mp4
    # ports:
    #   - 8189:8189
    #   - 8554:8554
    #   - 1935:1935
    #   - 8888:8888
    #   - 8889:8889
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    # start_command: # Add the command to start the server if needed

  - type: web
    name: stream-eo
    runtime: docker
    dockerfilePath: ./stream-eo.Dockerfile
    image:
      url: linuxserver/ffmpeg
    # env:
    #   # Add environment variables here if needed
    # volumes:
    #   - from: gizmo.mp4
    #     to: /video.mp4
    # ports: []
    # network_mode: host
    # command:
    #   [
    #     "-re",
    #     "-stream_loop",
    #     "-1",
    #     "-i",
    #     "/video.mp4",
    #     "-c",
    #     "copy",
    #     "-f",
    #     "rtsp",
    #     "-rtsp_transport",
    #     "tcp",
    #     "rtsp://localhost:8554/stream-eo",
    #   ]

  - type: web
    name: stream-ir
    runtime: docker
    dockerfilePath: ./stream-ir.Dockerfile
    image:
      url: linuxserver/ffmpeg
    # env:
    #   # Add environment variables here if needed
    # volumes:
    #   - from: gizmo.mp4
    #     to: /video.mp4
    # ports: []
    # network_mode: host
    # command:
    #   [
    #     "-re",
    #     "-stream_loop",
    #     "-1",
    #     "-i",
    #     "/video.mp4",
    #     "-c",
    #     "copy",
    #     "-f",
    #     "rtsp",
    #     "-rtsp_transport",
    #     "tcp",
    #     "rtsp://localhost:8554/stream-ir",
    #   ]
