services:
  - type: web
    name: server
    env: docker
    runtime: docker
    dockerfilePath: ./server.Dockerfile
    dockerContext: ./
    envVars:
      - key: "FFMPEG_INPUT_FILE"
        value: "/video.mp4"
      - key: "CONFIG_FILE"
        value: "/mediamtx.yml"

  - type: web
    name: stream-eo
    env: docker
    runtime: docker
    dockerfilePath: ./stream-eo.Dockerfile
    dockerContext: ./
    envVars:
      - key: "FFMPEG_INPUT_FILE"
        value: "/video.mp4"
      - key: "FFMPEG_OUTPUT_FORMAT"
        value: "rtsp"
      - key: "FFMPEG_OUTPUT_URL"
        value: "rtsp://localhost:8554/stream-eo"
      - key: "FFMPEG_INPUT_LOOP"
        value: "1"
      - key: "FFMPEG_TRANSPORT_PROTOCOL"
        value: "tcp"

  - type: web
    name: stream-ir
    env: docker
    runtime: docker
    dockerfilePath: ./stream-ir.Dockerfile
    dockerContext: ./
    envVars:
      - key: "FFMPEG_INPUT_FILE"
        value: "/video.mp4"
      - key: "FFMPEG_OUTPUT_FORMAT"
        value: "rtsp"
      - key: "FFMPEG_OUTPUT_URL"
        value: "rtsp://localhost:8554/stream-ir"
      - key: "FFMPEG_INPUT_LOOP"
        value: "1"
      - key: "FFMPEG_TRANSPORT_PROTOCOL"
        value: "tcp"
